apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: todo-data-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-springboot-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: springboot-app
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app: springboot-app
    spec:
      containers:
      - name: my-springboot-app
        image: devresourceacr.azurecr.io/devresourceacr:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 8085
        volumeMounts:
        - mountPath: /data
          name: todo-data-volume
      volumes:
      - name: todo-data-volume
        persistentVolumeClaim:
          claimName: todo-data-pvc
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: springboot-app
    k8s-app: springboot-app
  name: springboot-app
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 8085
  type: LoadBalancer
  selector:
    app: springboot-app
